// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHUJyqThLwvYTxRfYwDFv-mxFk5d_lo8',
    appId: '1:348778726866:web:25a4a9304ca3b2abdef40b',
    messagingSenderId: '348778726866',
    projectId: 'coco-rider-dev',
    authDomain: 'coco-rider-dev.firebaseapp.com',
    storageBucket: 'coco-rider-dev.appspot.com',
    measurementId: 'G-7428S45G1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIE_AY-jFC_LWvHlq7Rjqlw4GYXOG80I',
    appId: '1:348778726866:android:d0b6721f03f6125fdef40b',
    messagingSenderId: '348778726866',
    projectId: 'coco-rider-dev',
    storageBucket: 'coco-rider-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjr4nWIVTh0NeYNL_KgpV6Xwrth6UqXDI',
    appId: '1:348778726866:ios:c24fd21382c9c4cedef40b',
    messagingSenderId: '348778726866',
    projectId: 'coco-rider-dev',
    storageBucket: 'coco-rider-dev.appspot.com',
    iosBundleId: 'com.example.cocoRider',
  );
}
