import 'package:get/get.dart';

class CocoInternalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_CM': {
          InternalizationKeys.enterPhoneNumberText: 'ENTER YOUR PHONE NUMBER',
          InternalizationKeys.enterOTPCodeText:
              'ENTER THE OTP CODE WHICH HAS BEEN SENT',
          InternalizationKeys.nextText: 'Next',
          InternalizationKeys.hintForDepartureTextField: 'Departure',
          InternalizationKeys.hintForArrivalTextField: 'Arrival',
          InternalizationKeys.hintForReservationDateTextField: 'Today',
          InternalizationKeys.errorNonDigitInNumber:
              'Should only contain digits',
          InternalizationKeys.errorFormatPhoneNumber:
              'Wrong phone number format',
          InternalizationKeys.errorAutoRetrievalTimeOut:
              "Couldn't automatically retrieve the code.",
          InternalizationKeys.errorOccurred: 'An error occurred.',
          InternalizationKeys.successText: 'Successful',
          InternalizationKeys.errorText: 'Error',
          InternalizationKeys.notYetImplementedText:
              'Feature not yet implemented',
          InternalizationKeys.searchTitle: 'Search',
          InternalizationKeys.postARideTitle: 'Post',
          InternalizationKeys.yourRidesHistoryTitle: 'Coco rides',
          InternalizationKeys.inboxTitle: 'Messages',
          InternalizationKeys.profileTitle: 'Profile',
          ...AppStrings.en,
        },
        'fr_CM': {
          InternalizationKeys.enterPhoneNumberText:
              'ENTRER VOTRE NUMERO DE TELEPHONE',
          InternalizationKeys.enterOTPCodeText: 'ENTRER LE CODE OTP ENVOYÉ',
          InternalizationKeys.nextText: 'Suivant',
          InternalizationKeys.hintForDepartureTextField: 'Départ',
          InternalizationKeys.hintForArrivalTextField: 'Destination',
          InternalizationKeys.hintForReservationDateTextField: "Aujourd'hui",
          InternalizationKeys.errorNonDigitInNumber:
              'Doit seulement contenir des chiffres',
          InternalizationKeys.errorFormatPhoneNumber:
              'Le format du numero de téléphone est incorrect',
          InternalizationKeys.errorAutoRetrievalTimeOut:
              'Impossible de récupérer automatiquement le code.',
          InternalizationKeys.errorOccurred: "Une erreur s'est produite.",
          InternalizationKeys.successText: 'Réussi',
          InternalizationKeys.errorText: 'Erreur',
          InternalizationKeys.notYetImplementedText:
              'Fonctionnalité pas encore disponible',
          InternalizationKeys.searchTitle: 'Rechercher',
          InternalizationKeys.postARideTitle: 'Publier',
          InternalizationKeys.yourRidesHistoryTitle: 'Coco trajets',
          InternalizationKeys.inboxTitle: 'Messages',
          InternalizationKeys.profileTitle: 'Profil',
          ...AppStrings.fr,
        }
      };
}

class InternalizationKeys {
  static const enterPhoneNumberText = 'enterPhoneNumberText';
  static const enterOTPCodeText = 'enterOTPCodeText';
  static const nextText = 'nextText';
  static const countryCodeForPhoneNumberTextField = '+237';
  static const defaultTestPhoneNumber = '679001122';
  static const defaultTestVerificationId = 'ABC123XYZ';
  static const hintForPhoneNumberTextField = '000 000 000';
  static const hintForOTPDigitTextField = '0';
  static const hintForDepartureTextField = 'hintForDepartureTextField';
  static const hintForArrivalTextField = 'hintForReservationTextField';
  static const hintForReservationDateTextField =
      'hintForReservationDateTextField';
  static const hintForNumberOfReservationsTextField = '1';
  static const errorNonDigitInNumber = 'errorNonDigitInNumber';
  static const errorFormatPhoneNumber = 'errorFormatPhoneNumber';
  static const errorAutoRetrievalTimeOut = 'errorAutoRetrievalTimeOut';
  static const errorOccurred = 'errorOccurred';
  static const successText = 'successText';
  static const errorText = 'errorText';
  static const notYetImplementedText = 'notYetImplementedText';
  static const searchTitle = 'searchTitle';
  static const postARideTitle = 'postARideTitle';
  static const yourRidesHistoryTitle = 'yourRidesHistoryTitle';
  static const inboxTitle = 'inboxTitle';
  static const profileTitle = 'profileTitle';
}

/// Texts of the carpooling screens. Keys are used directly with `.tr`,
/// e.g. `'search.button'.tr`. Error codes from the API are keys too ("error.<code>").
class AppStrings {
  static const Map<String, String> en = {
    // Profile setup
    'profile.setupTitle': 'Tell us about you',
    'profile.firstName': 'First name',
    'profile.lastName': 'Last name',
    'profile.gender': 'Gender',
    'profile.language': 'Language',
    'profile.save': 'Save',
    'profile.edit': 'Edit my profile',
    'profile.logout': 'Log out',
    'profile.asPassenger': 'Passenger',
    'profile.asDriver': 'Driver',
    'profile.documents': 'My documents',
    'profile.missing': 'Missing: @docs',
    'profile.expired': 'Expired: @docs',
    'profile.suspended': 'Your account is suspended until @date.',
    'gender.female': 'Woman',
    'gender.male': 'Man',
    'gender.unspecified': 'Prefer not to say',
    'language.french': 'Français',
    'language.english': 'English',
    'status.incomplete': 'Documents missing',
    'status.manualReview': 'Being checked',
    'status.verified': 'Verified',
    'status.rejected': 'Document refused',
    // Documents
    'documents.title': 'My documents',
    'documents.intro': 'Passengers need their CNI and a selfie. Drivers also need their driving licence, insurance and carte grise.',
    'documents.upload': 'Add a photo',
    'documents.replace': 'Replace',
    'documents.camera': 'Take a photo',
    'documents.gallery': 'Choose from gallery',
    'documents.expiry': 'Expiry date',
    'documents.uploaded': 'Document sent',
    'documents.notSent': 'Not sent',
    'doc.nationalId': 'National ID card (CNI)',
    'doc.selfie': 'Selfie',
    'doc.driverLicence': 'Driving licence',
    'doc.insurance': 'Insurance certificate',
    'doc.vehicleRegistration': 'Carte grise',
    'docStatus.awaitingUpload': 'Not sent',
    'docStatus.submitted': 'Being checked',
    'docStatus.accepted': 'Accepted',
    'docStatus.needsReview': 'Being checked by our team',
    'docStatus.rejected': 'Refused',
    // Search
    'search.from': 'From',
    'search.to': 'To',
    'search.date': 'Date',
    'search.seats': 'Seats',
    'search.button': 'Search',
    'search.noResults': 'No trips for this search yet.',
    'search.results': '@count trip(s)',
    'trip.seatsLeft': '@count seat(s) left',
    'trip.perSeat': 'per seat',
    'trip.womenOnly': 'Women only',
    'trip.luggage': 'Luggage allowed',
    'trip.smoking': 'Smoking allowed',
    'trip.instant': 'Instant booking',
    'trip.onRequest': 'Driver confirms each booking',
    'trip.driver': 'Driver',
    'trip.vehicle': 'Vehicle',
    'trip.notes': 'Notes',
    'trip.newRating': 'New',
    'trip.details': 'Trip details',
    // Booking
    'booking.title': 'Book',
    'booking.payment': 'Payment to the driver',
    'booking.total': 'Total',
    'booking.confirm': 'Book',
    'booking.done': 'Booking sent',
    'booking.cancel': 'Cancel booking',
    'booking.cancelRule': 'Free cancellation until 24 hours before departure.',
    'booking.review': 'Rate this trip',
    'booking.driverPhone': 'Driver phone',
    'payment.cash': 'Cash',
    'payment.mtnMobileMoney': 'MTN Mobile Money',
    'payment.orangeMoney': 'Orange Money',
    'bookingStatus.pending': 'Waiting for the driver',
    'bookingStatus.confirmed': 'Confirmed',
    'bookingStatus.rejectedByDriver': 'Declined',
    'bookingStatus.cancelledByPassenger': 'Cancelled',
    'bookingStatus.tripCancelled': 'Trip cancelled',
    'bookingStatus.completed': 'Completed',
    'bookingStatus.noShow': 'No-show',
    'bookingStatus.expired': 'Expired (no answer)',
    // Driver
    'driver.bookings': 'Passengers',
    'driver.noBookings': 'No bookings yet.',
    'driver.accept': 'Accept',
    'driver.reject': 'Decline',
    'driver.noShow': 'Did not show up',
    'driver.cancelTrip': 'Cancel trip',
    'driver.completeTrip': 'Trip completed',
    'driver.cancelWarning': 'Cancelling less than 24 hours before departure gives you a strike.',
    // Publish
    'publish.title': 'Publish a trip',
    'publish.notVerified': 'Send your driver documents to publish trips.',
    'publish.intercity': 'Between cities',
    'publish.urban': 'In town',
    'publish.fromLandmark': 'Pick-up point (landmark)',
    'publish.toLandmark': 'Drop-off point (landmark)',
    'publish.time': 'Time',
    'publish.price': 'Price per seat (FCFA)',
    'publish.vehicle': 'Vehicle',
    'publish.addVehicle': 'Add a vehicle',
    'publish.button': 'Publish',
    'publish.done': 'Trip published',
    'vehicle.make': 'Make',
    'vehicle.model': 'Model',
    'vehicle.color': 'Color',
    'vehicle.plate': 'Plate number',
    'vehicle.seats': 'Passenger seats',
    // Rides
    'rides.asPassenger': 'My bookings',
    'rides.asDriver': 'My trips',
    'rides.none': 'Nothing here yet.',
    'review.title': 'Rate your trip',
    'review.comment': 'Comment (optional)',
    'review.send': 'Send',
    'review.thanks': 'Thank you for your review',
    'inbox.empty': 'No messages yet. You can write to the driver or the passengers from a booking.',
    'chat.hint': 'Write a message',
    'chat.send': 'Send',
    'chat.closed': 'This conversation is closed.',
    'chat.open': 'Message',
    'chat.read': 'Read',
    'chat.privacy': 'Stay polite. Never share codes or pay before the trip.',
    'common.cancel': 'Cancel',
    'common.retry': 'Retry',
    'common.confirm': 'Confirm',
    'common.required': 'Required',
    // API errors (the API sends stable codes)
    'error.booking.cancellation_window_closed': 'Bookings cannot be cancelled less than 24 hours before departure.',
    'error.booking.already_booked': 'You already have a booking on this trip.',
    'error.booking.women_only': 'This trip is reserved for women.',
    'error.trip.not_enough_seats': 'Not enough seats left on this trip.',
    'error.verification.passenger_not_verified': 'Your documents must be verified before you can book.',
    'error.verification.driver_not_verified': 'Your driver documents must be verified before you can publish.',
    'error.account.suspended': 'Your account is suspended.',
    'error.trip.departure_too_soon': 'The departure must be at least 30 minutes from now.',
    'error.vehicle.plate_taken': 'This plate number is already registered.',
    'error.document.expired': 'This document is expired.',
    'error.network': 'No internet connection.',
    'error.message.conversation_closed': 'This conversation is closed.',
    'error.message.too_long': 'The message is too long.',
  };

  static const Map<String, String> fr = {
    'profile.setupTitle': 'Parlez-nous de vous',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.gender': 'Sexe',
    'profile.language': 'Langue',
    'profile.save': 'Enregistrer',
    'profile.edit': 'Modifier mon profil',
    'profile.logout': 'Se déconnecter',
    'profile.asPassenger': 'Passager',
    'profile.asDriver': 'Conducteur',
    'profile.documents': 'Mes documents',
    'profile.missing': 'Manquant : @docs',
    'profile.expired': 'Expiré : @docs',
    'profile.suspended': "Votre compte est suspendu jusqu'au @date.",
    'gender.female': 'Femme',
    'gender.male': 'Homme',
    'gender.unspecified': 'Je préfère ne pas répondre',
    'language.french': 'Français',
    'language.english': 'English',
    'status.incomplete': 'Documents manquants',
    'status.manualReview': 'En vérification',
    'status.verified': 'Vérifié',
    'status.rejected': 'Document refusé',
    'documents.title': 'Mes documents',
    'documents.intro': 'Les passagers envoient leur CNI et un selfie. Les conducteurs ajoutent leur permis, leur assurance et leur carte grise.',
    'documents.upload': 'Ajouter une photo',
    'documents.replace': 'Remplacer',
    'documents.camera': 'Prendre une photo',
    'documents.gallery': 'Choisir dans la galerie',
    'documents.expiry': "Date d'expiration",
    'documents.uploaded': 'Document envoyé',
    'documents.notSent': 'Non envoyé',
    'doc.nationalId': "Carte nationale d'identité (CNI)",
    'doc.selfie': 'Selfie',
    'doc.driverLicence': 'Permis de conduire',
    'doc.insurance': "Attestation d'assurance",
    'doc.vehicleRegistration': 'Carte grise',
    'docStatus.awaitingUpload': 'Non envoyé',
    'docStatus.submitted': 'En vérification',
    'docStatus.accepted': 'Accepté',
    'docStatus.needsReview': 'En vérification par notre équipe',
    'docStatus.rejected': 'Refusé',
    'search.from': 'Départ',
    'search.to': 'Destination',
    'search.date': 'Date',
    'search.seats': 'Places',
    'search.button': 'Rechercher',
    'search.noResults': 'Aucun trajet pour cette recherche pour le moment.',
    'search.results': '@count trajet(s)',
    'trip.seatsLeft': '@count place(s) restante(s)',
    'trip.perSeat': 'par place',
    'trip.womenOnly': 'Entre femmes',
    'trip.luggage': 'Bagages acceptés',
    'trip.smoking': 'Fumeurs acceptés',
    'trip.instant': 'Réservation immédiate',
    'trip.onRequest': 'Le conducteur confirme chaque réservation',
    'trip.driver': 'Conducteur',
    'trip.vehicle': 'Véhicule',
    'trip.notes': 'Remarques',
    'trip.newRating': 'Nouveau',
    'trip.details': 'Détails du trajet',
    'booking.title': 'Réserver',
    'booking.payment': 'Paiement au conducteur',
    'booking.total': 'Total',
    'booking.confirm': 'Réserver',
    'booking.done': 'Réservation envoyée',
    'booking.cancel': 'Annuler la réservation',
    'booking.cancelRule': "Annulation gratuite jusqu'à 24 heures avant le départ.",
    'booking.review': 'Noter ce trajet',
    'booking.driverPhone': 'Téléphone du conducteur',
    'payment.cash': 'Espèces',
    'payment.mtnMobileMoney': 'MTN Mobile Money',
    'payment.orangeMoney': 'Orange Money',
    'bookingStatus.pending': 'En attente du conducteur',
    'bookingStatus.confirmed': 'Confirmée',
    'bookingStatus.rejectedByDriver': 'Refusée',
    'bookingStatus.cancelledByPassenger': 'Annulée',
    'bookingStatus.tripCancelled': 'Trajet annulé',
    'bookingStatus.completed': 'Terminée',
    'bookingStatus.noShow': 'Absent',
    'bookingStatus.expired': 'Expirée (sans réponse)',
    'driver.bookings': 'Passagers',
    'driver.noBookings': 'Aucune réservation pour le moment.',
    'driver.accept': 'Accepter',
    'driver.reject': 'Refuser',
    'driver.noShow': "Ne s'est pas présenté",
    'driver.cancelTrip': 'Annuler le trajet',
    'driver.completeTrip': 'Trajet terminé',
    'driver.cancelWarning': 'Annuler moins de 24 heures avant le départ vous vaut un avertissement.',
    'publish.title': 'Publier un trajet',
    'publish.notVerified': 'Envoyez vos documents de conducteur pour publier des trajets.',
    'publish.intercity': 'Entre villes',
    'publish.urban': 'En ville',
    'publish.fromLandmark': 'Point de départ (repère)',
    'publish.toLandmark': "Point d'arrivée (repère)",
    'publish.time': 'Heure',
    'publish.price': 'Prix par place (FCFA)',
    'publish.vehicle': 'Véhicule',
    'publish.addVehicle': 'Ajouter un véhicule',
    'publish.button': 'Publier',
    'publish.done': 'Trajet publié',
    'vehicle.make': 'Marque',
    'vehicle.model': 'Modèle',
    'vehicle.color': 'Couleur',
    'vehicle.plate': "Numéro d'immatriculation",
    'vehicle.seats': 'Places passagers',
    'rides.asPassenger': 'Mes réservations',
    'rides.asDriver': 'Mes trajets',
    'rides.none': "Rien pour l'instant.",
    'review.title': 'Notez votre trajet',
    'review.comment': 'Commentaire (facultatif)',
    'review.send': 'Envoyer',
    'review.thanks': 'Merci pour votre avis',
    'inbox.empty': "Pas encore de messages. Vous pouvez écrire au conducteur ou aux passagers depuis une réservation.",
    'chat.hint': 'Écrire un message',
    'chat.send': 'Envoyer',
    'chat.closed': 'Cette conversation est fermée.',
    'chat.open': 'Message',
    'chat.read': 'Lu',
    'chat.privacy': "Restez courtois. Ne partagez jamais de code et ne payez pas avant le trajet.",
    'common.cancel': 'Annuler',
    'common.retry': 'Réessayer',
    'common.confirm': 'Confirmer',
    'common.required': 'Obligatoire',
    'error.booking.cancellation_window_closed': 'Une réservation ne peut plus être annulée moins de 24 heures avant le départ.',
    'error.booking.already_booked': 'Vous avez déjà une réservation sur ce trajet.',
    'error.booking.women_only': 'Ce trajet est réservé aux femmes.',
    'error.trip.not_enough_seats': 'Il ne reste pas assez de places sur ce trajet.',
    'error.verification.passenger_not_verified': 'Vos documents doivent être vérifiés avant de réserver.',
    'error.verification.driver_not_verified': 'Vos documents de conducteur doivent être vérifiés avant de publier.',
    'error.account.suspended': 'Votre compte est suspendu.',
    'error.trip.departure_too_soon': 'Le départ doit être dans au moins 30 minutes.',
    'error.vehicle.plate_taken': "Ce numéro d'immatriculation est déjà enregistré.",
    'error.document.expired': 'Ce document est expiré.',
    'error.network': 'Pas de connexion internet.',
    'error.message.conversation_closed': 'Cette conversation est fermée.',
    'error.message.too_long': 'Le message est trop long.',
  };
}
