import 'package:get/get.dart';

class CocoInternalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_CM': {
          InternalizationKeys.enterPhoneNumberText: 'ENTER YOUR PHONE NUMBER',
          InternalizationKeys.enterOTPCodeText:
              'ENTER THE OTP CODE WHICH HAS BEEN SENT',
          InternalizationKeys.nextText: 'Next',
          InternalizationKeys.hintForDepartureTextField: 'Departure',
          InternalizationKeys.hintForArrivalTextField: 'Arrival',
          InternalizationKeys.hintForReservationDateTextField: 'Today',
          InternalizationKeys.errorNonDigitInNumber:
              'Should only contain digits',
          InternalizationKeys.errorFormatPhoneNumber:
              'Wrong phone number format',
          InternalizationKeys.errorAutoRetrievalTimeOut:
              "Couldn't automatically retrieve the code.",
          InternalizationKeys.errorOccurred: 'An error occurred.',
          InternalizationKeys.successText: 'Successful',
          InternalizationKeys.errorText: 'Error',
          InternalizationKeys.notYetImplementedText:
              'Feature not yet implemented',
          InternalizationKeys.searchTitle: 'Search',
          InternalizationKeys.postARideTitle: 'Post',
          InternalizationKeys.yourRidesHistoryTitle: 'History',
          InternalizationKeys.inboxTitle: 'Messages',
          InternalizationKeys.profileTitle: 'Profile',
          ...AppStrings.en,
        },
        'fr_CM': {
          InternalizationKeys.enterPhoneNumberText:
              'ENTRER VOTRE NUMERO DE TELEPHONE',
          InternalizationKeys.enterOTPCodeText: 'ENTRER LE CODE OTP ENVOYÉ',
          InternalizationKeys.nextText: 'Suivant',
          InternalizationKeys.hintForDepartureTextField: 'Départ',
          InternalizationKeys.hintForArrivalTextField: 'Destination',
          InternalizationKeys.hintForReservationDateTextField: "Aujourd'hui",
          InternalizationKeys.errorNonDigitInNumber:
              'Doit seulement contenir des chiffres',
          InternalizationKeys.errorFormatPhoneNumber:
              'Le format du numero de téléphone est incorrect',
          InternalizationKeys.errorAutoRetrievalTimeOut:
              'Impossible de récupérer automatiquement le code.',
          InternalizationKeys.errorOccurred: "Une erreur s'est produite.",
          InternalizationKeys.successText: 'Réussi',
          InternalizationKeys.errorText: 'Erreur',
          InternalizationKeys.notYetImplementedText:
              'Fonctionnalité pas encore disponible',
          InternalizationKeys.searchTitle: 'Rechercher',
          InternalizationKeys.postARideTitle: 'Publier',
          InternalizationKeys.yourRidesHistoryTitle: 'Historique',
          InternalizationKeys.inboxTitle: 'Messages',
          InternalizationKeys.profileTitle: 'Profil',
          ...AppStrings.fr,
        }
      };
}

class InternalizationKeys {
  static const enterPhoneNumberText = 'enterPhoneNumberText';
  static const enterOTPCodeText = 'enterOTPCodeText';
  static const nextText = 'nextText';
  static const countryCodeForPhoneNumberTextField = '+237';
  static const defaultTestPhoneNumber = '679001122';
  static const defaultTestVerificationId = 'ABC123XYZ';
  static const hintForPhoneNumberTextField = '000 000 000';
  static const hintForOTPDigitTextField = '0';
  static const hintForDepartureTextField = 'hintForDepartureTextField';
  static const hintForArrivalTextField = 'hintForReservationTextField';
  static const hintForReservationDateTextField =
      'hintForReservationDateTextField';
  static const hintForNumberOfReservationsTextField = '1';
  static const errorNonDigitInNumber = 'errorNonDigitInNumber';
  static const errorFormatPhoneNumber = 'errorFormatPhoneNumber';
  static const errorAutoRetrievalTimeOut = 'errorAutoRetrievalTimeOut';
  static const errorOccurred = 'errorOccurred';
  static const successText = 'successText';
  static const errorText = 'errorText';
  static const notYetImplementedText = 'notYetImplementedText';
  static const searchTitle = 'searchTitle';
  static const postARideTitle = 'postARideTitle';
  static const yourRidesHistoryTitle = 'yourRidesHistoryTitle';
  static const inboxTitle = 'inboxTitle';
  static const profileTitle = 'profileTitle';
}

/// Texts of the carpooling screens. Keys are used directly with `.tr`,
/// e.g. `'search.button'.tr`. Error codes from the API are keys too ("error.<code>").
class AppStrings {
  static const Map<String, String> en = {
    'brand.tagline': 'a little more together.',
    'search.anyDate': 'Any date',
    'search.anySeats': 'Passengers',
    'search.clearFilter': 'Remove this filter',
    // Figma redesign
    'nav.home': 'Home',
    'nav.cocoRide': 'Drive',
    'nav.history': 'History',
    'home.tagline': 'Where are you going today?',
    'home.subtitle': 'Share the cost of your trips across Cameroon.',
    'search.title': 'Find a trip',
    'search.useLocation': 'Use my location',
    'search.locationDenied': 'Allow location access to fill in your city.',
    'search.locationFailed': 'Your position could not be found.',
    'search.seatCount': '@count seat(s)',
    'search.viewTrip': 'View trip details',
    'ticket.departure': 'Departure',
    'ticket.seats': 'Seats left',
    'ticket.price': 'Price',
    'tripKind.intercity': 'Intercity',
    'tripKind.urban': 'In town',
    'trip.availableSeats': 'Available seats',
    'trip.pricePerSeat': 'Price per seat',
    'trip.noLuggage': 'No luggage',
    'trip.noSmoking': 'No smoking',
    'trip.reviews': '@count review(s)',
    'profile.title': 'My profile',
    'profile.open': 'Open my profile',
    'profile.verifiedMember': 'Verified member',
    'profile.completeVerification': 'Verify your account',
    'profile.phone': 'Phone number',
    'profile.phoneHelp': 'Drivers and passengers call you on this number once a booking is confirmed.',
    'profile.phoneNotVerified': 'Number not verified by SMS',
    'inbox.title': 'Messages',
    'publish.stepPickUp': 'Pick-up',
    'publish.stepDropOff': 'Drop-off',
    'publish.stepDetails': 'Car & details',
    'publish.pickUpIntro': 'Where and when do you leave?',
    'publish.dropOffIntro': 'Where do you drop your passengers?',
    'publish.detailsIntro': 'Your car, seats and price',
    'publish.fromCity': 'Departure city',
    'publish.toCity': 'Destination city',
    'publish.landmarkHelp': 'A place everyone knows: carrefour, petrol station, market…',
    'publish.addVehicleFirst': 'Add a vehicle first',
    'publish.priceRange': 'Between 1 and 100,000 FCFA',
    'publish.seats': 'Seats offered',
    'publish.notesHint': 'Message to passengers (optional)',
    'publish.doneInstant': 'Passengers can book right away.',
    'publish.doneOnRequest': 'You will accept or decline each request.',
    'publish.seeMyTrips': 'See my trips',
    'publish.another': 'Publish another trip',
    'vehicle.general': 'Vehicle',
    'vehicle.identification': 'Identification',
    'vehicle.plateHint': 'Plate number (e.g. LT 123 AB)',
    'vehicle.save': 'Save the vehicle',
    'history.title': 'History',
    'history.manageTrip': 'Manage the trip',
    'history.filter.all': 'All',
    'history.filter.scheduled': 'Upcoming',
    'history.filter.ongoing': 'Ongoing',
    'history.filter.completed': 'Completed',
    'history.filter.cancelled': 'Cancelled',
    'booking.seats': 'Seats to book',
    'booking.yourSeats': '@count seat(s)',
    'booking.paymentNote': 'You pay the driver directly; on-go does not take any money.',
    'booking.seatsLine': '@count × @price',
    'booking.totalToPay': 'Total to pay',
    'booking.request': 'Send a booking request',
    'booking.requestSent': 'Request sent',
    'booking.waitingDriver': 'Waiting for @name to accept your request.',
    'booking.seeMyBookings': 'See my bookings',
    'booking.cancelConfirm': 'Cancel this booking?',
    'payment.cash.hint': 'Pay the driver in cash',
    'payment.mtnMobileMoney.hint': 'Send to the driver by MTN MoMo',
    'payment.orangeMoney.hint': 'Send to the driver by Orange Money',
    'driver.passengerPhone': 'Passenger phone',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.close': 'Close',
    'auth.title': 'Let’s get started! 👋',
    'auth.subtitlePhone': 'Enter your phone number to sign in or create your account.',
    'auth.subtitleEmail': 'Enter your email address to sign in or create your account.',
    'auth.phoneLabel': 'Phone number',
    'auth.emailLabel': 'Email address',
    'auth.emailHint': 'name@example.com',
    'auth.invalidPhone': 'Enter a Cameroonian number: 9 digits, e.g. 690 00 00 01.',
    'auth.invalidEmail': 'Enter a valid email address.',
    'auth.useEmail': 'Use an email address',
    'auth.usePhone': 'Use a phone number',
    'auth.sendCode': 'Get my code',
    'auth.codeTitle': 'Enter the code 🔐',
    'auth.codeSentPhone': 'We sent a 6-digit code by SMS to @to.',
    'auth.codeSentEmail': 'We sent a 6-digit code to @to. Check your spam folder too.',
    'auth.resendIn': 'Resend the code in @seconds s',
    'auth.resend': 'Resend the code',
    'auth.codeResent': 'New code sent',
    'auth.error.generic': 'Something went wrong. Try again.',
    'auth.error.CodeMismatchException': 'Wrong code. Check it and try again.',
    'auth.error.ExpiredCodeException': 'This code has expired. Ask for a new one.',
    'auth.error.LimitExceededException': 'Too many attempts. Wait a few minutes.',
    'auth.error.TooManyRequestsException': 'Too many attempts. Wait a few minutes.',
    'auth.error.NotAuthorizedException': 'This code is no longer valid. Ask for a new one.',
    'auth.error.network-request-failed': 'No internet connection.',
    'auth.error.code-not-requested': 'Ask for a code first.',
    'auth.error.CodeDeliveryFailureException': 'The code could not be sent. Check the number or address.',
    'auth.error.InvalidParameterException': 'Check the number or address and try again.',
    'auth.error.UnexpectedChallenge': 'Sign-in is not possible right now. Try again in a moment.',
    'error.profile.invalid_phone': 'Enter a Cameroonian phone number.',
    'error.profile.phone_taken': 'This phone number is already used by another account.',
    'error.profile.phone_locked': 'A number verified by SMS cannot be changed.',
    // Profile setup
    'profile.setupTitle': 'Tell us about you',
    'profile.firstName': 'First name',
    'profile.lastName': 'Last name',
    'profile.language': 'Language',
    'profile.save': 'Save',
    'profile.edit': 'Edit my profile',
    'profile.logout': 'Log out',
    'profile.asPassenger': 'Passenger',
    'profile.asDriver': 'Driver',
    'profile.documents': 'My documents',
    'profile.missing': 'Missing: @docs',
    'profile.expired': 'Expired: @docs',
    'profile.suspended': 'Your account is suspended until @date.',
    'language.french': 'Français',
    'language.english': 'English',
    'status.incomplete': 'Documents missing',
    'status.manualReview': 'Being checked',
    'status.verified': 'Verified',
    'status.rejected': 'Document refused',
    // Documents
    'documents.title': 'My documents',
    'documents.intro': 'Passengers need their CNI and a selfie. Drivers also need their driving licence, insurance and carte grise.',
    'documents.upload': 'Add a photo',
    'documents.replace': 'Replace',
    'documents.camera': 'Take a photo',
    'documents.gallery': 'Choose from gallery',
    'documents.expiry': 'Expiry date',
    'documents.uploaded': 'Document sent',
    'documents.notSent': 'Not sent',
    'doc.nationalId': 'National ID card (CNI)',
    'doc.selfie': 'Selfie',
    'doc.driverLicence': 'Driving licence',
    'doc.insurance': 'Insurance certificate',
    'doc.vehicleRegistration': 'Carte grise',
    'docStatus.awaitingUpload': 'Not sent',
    'docStatus.submitted': 'Being checked',
    'docStatus.accepted': 'Accepted',
    'docStatus.needsReview': 'Being checked by our team',
    'docStatus.rejected': 'Refused',
    // Search
    'search.from': 'From',
    'search.to': 'To',
    'search.date': 'Date',
    'search.seats': 'Seats',
    'search.button': 'Search',
    'search.noResults': 'No trips for this search yet.',
    'search.results': '@count trip(s)',
    'trip.seatsLeft': '@count seat(s) left',
    'trip.perSeat': 'per seat',
    'trip.luggage': 'Luggage allowed',
    'trip.smoking': 'Smoking allowed',
    'trip.instant': 'Instant booking',
    'trip.onRequest': 'Driver confirms each booking',
    'trip.driver': 'Driver',
    'trip.vehicle': 'Vehicle',
    'trip.notes': 'Notes',
    'trip.newRating': 'New',
    'trip.details': 'Trip details',
    // Booking
    'booking.title': 'Book',
    'booking.payment': 'Payment to the driver',
    'booking.total': 'Total',
    'booking.confirm': 'Book',
    'booking.done': 'Booking confirmed',
    'booking.cancel': 'Cancel booking',
    'booking.cancelRule': 'Free cancellation until 24 hours before departure.',
    'booking.review': 'Rate this trip',
    'booking.driverPhone': 'Driver phone',
    'payment.cash': 'Cash',
    'payment.mtnMobileMoney': 'MTN Mobile Money',
    'payment.orangeMoney': 'Orange Money',
    'bookingStatus.pending': 'Waiting for the driver',
    'bookingStatus.confirmed': 'Confirmed',
    'bookingStatus.rejectedByDriver': 'Declined',
    'bookingStatus.cancelledByPassenger': 'Cancelled',
    'bookingStatus.tripCancelled': 'Trip cancelled',
    'bookingStatus.completed': 'Completed',
    'bookingStatus.noShow': 'No-show',
    'bookingStatus.expired': 'Expired (no answer)',
    // Driver
    'driver.bookings': 'Passengers',
    'driver.noBookings': 'No bookings yet.',
    'driver.accept': 'Accept',
    'driver.reject': 'Decline',
    'driver.noShow': 'Did not show up',
    'driver.cancelTrip': 'Cancel trip',
    'driver.completeTrip': 'Trip completed',
    'driver.cancelWarning': 'Cancelling less than 24 hours before departure gives you a strike.',
    // Publish
    'publish.title': 'Create a trip',
    'publish.notVerified': 'Send your driver documents to publish trips.',
    'publish.intercity': 'Between cities',
    'publish.urban': 'In town',
    'publish.fromLandmark': 'Pick-up point (landmark)',
    'publish.toLandmark': 'Drop-off point (landmark)',
    'publish.time': 'Time',
    'publish.price': 'Price per seat (FCFA)',
    'publish.vehicle': 'Vehicle',
    'publish.addVehicle': 'Add a vehicle',
    'publish.button': 'Publish',
    'publish.done': 'Trip published',
    'vehicle.make': 'Make',
    'vehicle.model': 'Model',
    'vehicle.color': 'Color',
    'vehicle.plate': 'Plate number',
    'vehicle.seats': 'Passenger seats',
    // Rides
    'rides.asPassenger': 'My bookings',
    'rides.asDriver': 'My trips',
    'rides.none': 'Nothing here yet.',
    'review.title': 'Rate your trip',
    'review.comment': 'Comment (optional)',
    'review.send': 'Send',
    'review.thanks': 'Thank you for your review',
    'inbox.empty': 'No messages yet. You can write to the driver or the passengers from a booking.',
    'chat.hint': 'Write a message',
    'chat.send': 'Send',
    'chat.closed': 'This conversation is closed.',
    'chat.open': 'Message',
    'chat.read': 'Read',
    'chat.privacy': 'Stay polite. Never share codes or pay before the trip.',
    'tracking.title': 'Follow the trip',
    'tracking.follow': 'Follow live',
    'tracking.waiting': 'The driver has not started sharing their position yet.',
    'tracking.live': 'Live position',
    'tracking.lastSeen': 'Last position at @time',
    'tracking.over': 'This trip is over.',
    'tracking.distance': '@km km from @city (as the crow flies)',
    'tracking.share': 'Share with a relative',
    'tracking.shareMessage': 'Follow my on-go trip live:',
    'tracking.start': 'Share my position',
    'tracking.stop': 'Stop sharing',
    'tracking.sharing': 'Passengers see your position. Last sent at @time.',
    'tracking.keepOpen': 'Keep the app open during the trip so your position is updated.',
    'tracking.permission': 'Allow location access to share your position.',
    'common.cancel': 'Cancel',
    'common.retry': 'Retry',
    'common.confirm': 'Confirm',
    'common.required': 'Required',
    // API errors (the API sends stable codes)
    'error.booking.cancellation_window_closed': 'Bookings cannot be cancelled less than 24 hours before departure.',
    'error.booking.already_booked': 'You already have a booking on this trip.',
    'error.trip.not_enough_seats': 'Not enough seats left on this trip.',
    'error.verification.passenger_not_verified': 'Your documents must be verified before you can book.',
    'error.verification.driver_not_verified': 'Your driver documents must be verified before you can publish.',
    'error.account.suspended': 'Your account is suspended.',
    'error.trip.departure_too_soon': 'The departure must be at least 30 minutes from now.',
    'error.vehicle.plate_taken': 'This plate number is already registered.',
    'error.document.expired': 'This document is expired.',
    'error.network': 'No internet connection.',
    'error.message.conversation_closed': 'This conversation is closed.',
    'error.message.too_long': 'The message is too long.',
  };

  static const Map<String, String> fr = {
    'brand.tagline': 'un peu plus ensemble.',
    'search.anyDate': 'Toutes les dates',
    'search.anySeats': 'Passagers',
    'search.clearFilter': 'Retirer ce filtre',
    // Figma redesign
    'nav.home': 'Accueil',
    'nav.cocoRide': 'Conduire',
    'nav.history': 'Historique',
    'home.tagline': 'Où allez-vous aujourd’hui ?',
    'home.subtitle': 'Partagez les frais de route partout au Cameroun.',
    'search.title': 'Rechercher un trajet',
    'search.useLocation': 'Utiliser ma position',
    'search.locationDenied': 'Autorisez la localisation pour remplir votre ville.',
    'search.locationFailed': 'Votre position n’a pas pu être trouvée.',
    'search.seatCount': '@count place(s)',
    'search.viewTrip': 'Voir le trajet',
    'ticket.departure': 'Départ',
    'ticket.seats': 'Places restantes',
    'ticket.price': 'Prix',
    'tripKind.intercity': 'Interurbain',
    'tripKind.urban': 'En ville',
    'trip.availableSeats': 'Places disponibles',
    'trip.pricePerSeat': 'Prix par place',
    'trip.noLuggage': 'Pas de bagages',
    'trip.noSmoking': 'Non-fumeur',
    'trip.reviews': '@count avis',
    'profile.title': 'Mon profil',
    'profile.open': 'Ouvrir mon profil',
    'profile.verifiedMember': 'Membre vérifié',
    'profile.completeVerification': 'Vérifiez votre compte',
    'profile.phone': 'Numéro de téléphone',
    'profile.phoneHelp': 'Conducteurs et passagers vous appellent à ce numéro une fois la réservation confirmée.',
    'profile.phoneNotVerified': 'Numéro non vérifié par SMS',
    'inbox.title': 'Messages',
    'publish.stepPickUp': 'Départ',
    'publish.stepDropOff': 'Arrivée',
    'publish.stepDetails': 'Véhicule',
    'publish.pickUpIntro': 'D’où et quand partez-vous ?',
    'publish.dropOffIntro': 'Où déposez-vous vos passagers ?',
    'publish.detailsIntro': 'Votre véhicule, vos places et votre prix',
    'publish.fromCity': 'Ville de départ',
    'publish.toCity': 'Ville d’arrivée',
    'publish.landmarkHelp': 'Un lieu connu de tous : carrefour, station, marché…',
    'publish.addVehicleFirst': 'Ajoutez d’abord un véhicule',
    'publish.priceRange': 'Entre 1 et 100 000 FCFA',
    'publish.seats': 'Places proposées',
    'publish.notesHint': 'Message aux passagers (facultatif)',
    'publish.doneInstant': 'Les passagers peuvent réserver tout de suite.',
    'publish.doneOnRequest': 'Vous accepterez ou refuserez chaque demande.',
    'publish.seeMyTrips': 'Voir mes trajets',
    'publish.another': 'Publier un autre trajet',
    'vehicle.general': 'Véhicule',
    'vehicle.identification': 'Identification',
    'vehicle.plateHint': 'Immatriculation (ex. LT 123 AB)',
    'vehicle.save': 'Enregistrer le véhicule',
    'history.title': 'Historique',
    'history.manageTrip': 'Gérer le trajet',
    'history.filter.all': 'Tous',
    'history.filter.scheduled': 'À venir',
    'history.filter.ongoing': 'En cours',
    'history.filter.completed': 'Terminés',
    'history.filter.cancelled': 'Annulés',
    'booking.seats': 'Places à réserver',
    'booking.yourSeats': '@count place(s)',
    'booking.paymentNote': 'Vous payez directement le conducteur ; on-go ne prend aucun argent.',
    'booking.seatsLine': '@count × @price',
    'booking.totalToPay': 'Total à payer',
    'booking.request': 'Envoyer une demande',
    'booking.requestSent': 'Demande envoyée',
    'booking.waitingDriver': 'En attente de l’accord de @name.',
    'booking.seeMyBookings': 'Voir mes réservations',
    'booking.cancelConfirm': 'Annuler cette réservation ?',
    'payment.cash.hint': 'Payez le conducteur en espèces',
    'payment.mtnMobileMoney.hint': 'Envoyez au conducteur par MTN MoMo',
    'payment.orangeMoney.hint': 'Envoyez au conducteur par Orange Money',
    'driver.passengerPhone': 'Téléphone du passager',
    'common.continue': 'Continuer',
    'common.back': 'Retour',
    'common.close': 'Fermer',
    'auth.title': 'Commençons ! 👋',
    'auth.subtitlePhone': 'Entrez votre numéro de téléphone pour vous connecter ou créer votre compte.',
    'auth.subtitleEmail': 'Entrez votre adresse e-mail pour vous connecter ou créer votre compte.',
    'auth.phoneLabel': 'Numéro de téléphone',
    'auth.emailLabel': 'Adresse e-mail',
    'auth.emailHint': 'nom@exemple.com',
    'auth.invalidPhone': 'Entrez un numéro camerounais : 9 chiffres, ex. 690 00 00 01.',
    'auth.invalidEmail': 'Entrez une adresse e-mail valide.',
    'auth.useEmail': 'Utiliser une adresse e-mail',
    'auth.usePhone': 'Utiliser un numéro de téléphone',
    'auth.sendCode': 'Recevoir mon code',
    'auth.codeTitle': 'Entrez le code 🔐',
    'auth.codeSentPhone': 'Nous avons envoyé un code à 6 chiffres par SMS au @to.',
    'auth.codeSentEmail': 'Nous avons envoyé un code à 6 chiffres à @to. Pensez à vérifier vos spams.',
    'auth.resendIn': 'Renvoyer le code dans @seconds s',
    'auth.resend': 'Renvoyer le code',
    'auth.codeResent': 'Nouveau code envoyé',
    'auth.error.generic': 'Une erreur est survenue. Réessayez.',
    'auth.error.CodeMismatchException': 'Code incorrect. Vérifiez-le et réessayez.',
    'auth.error.ExpiredCodeException': 'Ce code a expiré. Demandez-en un nouveau.',
    'auth.error.LimitExceededException': 'Trop de tentatives. Patientez quelques minutes.',
    'auth.error.TooManyRequestsException': 'Trop de tentatives. Patientez quelques minutes.',
    'auth.error.NotAuthorizedException': 'Ce code n’est plus valable. Demandez-en un nouveau.',
    'auth.error.network-request-failed': 'Pas de connexion internet.',
    'auth.error.code-not-requested': 'Demandez d’abord un code.',
    'auth.error.CodeDeliveryFailureException': 'Le code n’a pas pu être envoyé. Vérifiez le numéro ou l’adresse.',
    'auth.error.InvalidParameterException': 'Vérifiez le numéro ou l’adresse et réessayez.',
    'auth.error.UnexpectedChallenge': 'La connexion est impossible pour le moment. Réessayez dans un instant.',
    'error.profile.invalid_phone': 'Entrez un numéro de téléphone camerounais.',
    'error.profile.phone_taken': 'Ce numéro est déjà utilisé par un autre compte.',
    'error.profile.phone_locked': 'Un numéro vérifié par SMS ne peut pas être modifié.',
    'profile.setupTitle': 'Parlez-nous de vous',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.language': 'Langue',
    'profile.save': 'Enregistrer',
    'profile.edit': 'Modifier mon profil',
    'profile.logout': 'Se déconnecter',
    'profile.asPassenger': 'Passager',
    'profile.asDriver': 'Conducteur',
    'profile.documents': 'Mes documents',
    'profile.missing': 'Manquant : @docs',
    'profile.expired': 'Expiré : @docs',
    'profile.suspended': "Votre compte est suspendu jusqu'au @date.",
    'language.french': 'Français',
    'language.english': 'English',
    'status.incomplete': 'Documents manquants',
    'status.manualReview': 'En vérification',
    'status.verified': 'Vérifié',
    'status.rejected': 'Document refusé',
    'documents.title': 'Mes documents',
    'documents.intro': 'Les passagers envoient leur CNI et un selfie. Les conducteurs ajoutent leur permis, leur assurance et leur carte grise.',
    'documents.upload': 'Ajouter une photo',
    'documents.replace': 'Remplacer',
    'documents.camera': 'Prendre une photo',
    'documents.gallery': 'Choisir dans la galerie',
    'documents.expiry': "Date d'expiration",
    'documents.uploaded': 'Document envoyé',
    'documents.notSent': 'Non envoyé',
    'doc.nationalId': "Carte nationale d'identité (CNI)",
    'doc.selfie': 'Selfie',
    'doc.driverLicence': 'Permis de conduire',
    'doc.insurance': "Attestation d'assurance",
    'doc.vehicleRegistration': 'Carte grise',
    'docStatus.awaitingUpload': 'Non envoyé',
    'docStatus.submitted': 'En vérification',
    'docStatus.accepted': 'Accepté',
    'docStatus.needsReview': 'En vérification par notre équipe',
    'docStatus.rejected': 'Refusé',
    'search.from': 'Départ',
    'search.to': 'Destination',
    'search.date': 'Date',
    'search.seats': 'Places',
    'search.button': 'Rechercher',
    'search.noResults': 'Aucun trajet pour cette recherche pour le moment.',
    'search.results': '@count trajet(s)',
    'trip.seatsLeft': '@count place(s) restante(s)',
    'trip.perSeat': 'par place',
    'trip.luggage': 'Bagages acceptés',
    'trip.smoking': 'Fumeurs acceptés',
    'trip.instant': 'Réservation immédiate',
    'trip.onRequest': 'Le conducteur confirme chaque réservation',
    'trip.driver': 'Conducteur',
    'trip.vehicle': 'Véhicule',
    'trip.notes': 'Remarques',
    'trip.newRating': 'Nouveau',
    'trip.details': 'Détails du trajet',
    'booking.title': 'Réserver',
    'booking.payment': 'Paiement au conducteur',
    'booking.total': 'Total',
    'booking.confirm': 'Réserver',
    'booking.done': 'Réservation confirmée',
    'booking.cancel': 'Annuler la réservation',
    'booking.cancelRule': "Annulation gratuite jusqu'à 24 heures avant le départ.",
    'booking.review': 'Noter ce trajet',
    'booking.driverPhone': 'Téléphone du conducteur',
    'payment.cash': 'Espèces',
    'payment.mtnMobileMoney': 'MTN Mobile Money',
    'payment.orangeMoney': 'Orange Money',
    'bookingStatus.pending': 'En attente du conducteur',
    'bookingStatus.confirmed': 'Confirmée',
    'bookingStatus.rejectedByDriver': 'Refusée',
    'bookingStatus.cancelledByPassenger': 'Annulée',
    'bookingStatus.tripCancelled': 'Trajet annulé',
    'bookingStatus.completed': 'Terminée',
    'bookingStatus.noShow': 'Absent',
    'bookingStatus.expired': 'Expirée (sans réponse)',
    'driver.bookings': 'Passagers',
    'driver.noBookings': 'Aucune réservation pour le moment.',
    'driver.accept': 'Accepter',
    'driver.reject': 'Refuser',
    'driver.noShow': "Ne s'est pas présenté",
    'driver.cancelTrip': 'Annuler le trajet',
    'driver.completeTrip': 'Trajet terminé',
    'driver.cancelWarning': 'Annuler moins de 24 heures avant le départ vous vaut un avertissement.',
    'publish.title': 'Créer un trajet',
    'publish.notVerified': 'Envoyez vos documents de conducteur pour publier des trajets.',
    'publish.intercity': 'Entre villes',
    'publish.urban': 'En ville',
    'publish.fromLandmark': 'Point de départ (repère)',
    'publish.toLandmark': "Point d'arrivée (repère)",
    'publish.time': 'Heure',
    'publish.price': 'Prix par place (FCFA)',
    'publish.vehicle': 'Véhicule',
    'publish.addVehicle': 'Ajouter un véhicule',
    'publish.button': 'Publier',
    'publish.done': 'Trajet publié',
    'vehicle.make': 'Marque',
    'vehicle.model': 'Modèle',
    'vehicle.color': 'Couleur',
    'vehicle.plate': "Numéro d'immatriculation",
    'vehicle.seats': 'Places passagers',
    'rides.asPassenger': 'Mes réservations',
    'rides.asDriver': 'Mes trajets',
    'rides.none': "Rien pour l'instant.",
    'review.title': 'Notez votre trajet',
    'review.comment': 'Commentaire (facultatif)',
    'review.send': 'Envoyer',
    'review.thanks': 'Merci pour votre avis',
    'inbox.empty': "Pas encore de messages. Vous pouvez écrire au conducteur ou aux passagers depuis une réservation.",
    'chat.hint': 'Écrire un message',
    'chat.send': 'Envoyer',
    'chat.closed': 'Cette conversation est fermée.',
    'chat.open': 'Message',
    'chat.read': 'Lu',
    'chat.privacy': "Restez courtois. Ne partagez jamais de code et ne payez pas avant le trajet.",
    'tracking.title': 'Suivre le trajet',
    'tracking.follow': 'Suivre en direct',
    'tracking.waiting': "Le conducteur n'a pas encore commencé à partager sa position.",
    'tracking.live': 'Position en direct',
    'tracking.lastSeen': 'Dernière position à @time',
    'tracking.over': 'Ce trajet est terminé.',
    'tracking.distance': "À @km km de @city (à vol d'oiseau)",
    'tracking.share': 'Partager avec un proche',
    'tracking.shareMessage': 'Suivez mon trajet on-go en direct :',
    'tracking.start': 'Partager ma position',
    'tracking.stop': 'Arrêter le partage',
    'tracking.sharing': 'Les passagers voient votre position. Dernier envoi à @time.',
    'tracking.keepOpen': "Gardez l'application ouverte pendant le trajet pour que votre position soit mise à jour.",
    'tracking.permission': "Autorisez l'accès à la position pour la partager.",
    'common.cancel': 'Annuler',
    'common.retry': 'Réessayer',
    'common.confirm': 'Confirmer',
    'common.required': 'Obligatoire',
    'error.booking.cancellation_window_closed': 'Une réservation ne peut plus être annulée moins de 24 heures avant le départ.',
    'error.booking.already_booked': 'Vous avez déjà une réservation sur ce trajet.',
    'error.trip.not_enough_seats': 'Il ne reste pas assez de places sur ce trajet.',
    'error.verification.passenger_not_verified': 'Vos documents doivent être vérifiés avant de réserver.',
    'error.verification.driver_not_verified': 'Vos documents de conducteur doivent être vérifiés avant de publier.',
    'error.account.suspended': 'Votre compte est suspendu.',
    'error.trip.departure_too_soon': 'Le départ doit être dans au moins 30 minutes.',
    'error.vehicle.plate_taken': "Ce numéro d'immatriculation est déjà enregistré.",
    'error.document.expired': 'Ce document est expiré.',
    'error.network': 'Pas de connexion internet.',
    'error.message.conversation_closed': 'Cette conversation est fermée.',
    'error.message.too_long': 'Le message est trop long.',
  };
}
