// <auto-generated />
using System;
using CocoRider.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CocoRider.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CocoRiderDbContext))]
    [Migration("20261004224754_RemoveGender")]
    partial class RemoveGender
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CocoRider.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CommissionRateBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("commission_rate_basis_points");

                    b.Property<long>("CommissionXaf")
                        .HasColumnType("bigint")
                        .HasColumnName("commission_xaf");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_method");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TotalPriceXaf")
                        .HasColumnType("bigint")
                        .HasColumnName("total_price_xaf");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_bookings_trip_id");

                    b.HasIndex("PassengerId", "CreatedAt")
                        .HasDatabaseName("ix_bookings_passenger_id_created_at");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.HasIndex("BookingId", "SentAt")
                        .HasDatabaseName("ix_messages_booking_id_sent_at");

                    b.HasIndex("RecipientId", "ReadAt")
                        .HasDatabaseName("ix_messages_recipient_id_read_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Notifications.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_device_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_tokens_user_id");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_reviews_author_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_reviews_subject_id");

                    b.HasIndex("BookingId", "AuthorId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_booking_id_author_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Tracking.TripPosition", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<double?>("HeadingDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degrees");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("point");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<double?>("SpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kmh");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("TripId")
                        .HasName("pk_trip_positions");

                    b.ToTable("trip_positions", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Tracking.TripShare", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Token")
                        .HasName("pk_trip_shares");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_trip_shares_created_by_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_shares_trip_id");

                    b.ToTable("trip_shares", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<bool>("InstantBooking")
                        .HasColumnType("boolean")
                        .HasColumnName("instant_booking");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<bool>("LuggageAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("luggage_allowed");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<long>("PricePerSeatXaf")
                        .HasColumnType("bigint")
                        .HasColumnName("price_per_seat_xaf");

                    b.Property<int>("SeatsAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("seats_available");

                    b.Property<int>("SeatsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("seats_total");

                    b.Property<bool>("SmokingAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("smoking_allowed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_trips_vehicle_id");

                    b.HasIndex("DriverId", "DepartureAt")
                        .HasDatabaseName("ix_trips_driver_id_departure_at");

                    b.HasIndex("Status", "DepartureAt")
                        .HasDatabaseName("ix_trips_status_departure_at");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Users.Strike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_strikes");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_strikes_user_id_created_at");

                    b.ToTable("strikes", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CognitoSub")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cognito_sub");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DriverStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("driver_status");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PassengerStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("passenger_status");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_verified");

                    b.Property<DateTimeOffset?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_until");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CognitoSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_cognito_sub");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("PassengerSeats")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_seats");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plate_number");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vehicles_owner_id");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_plate_number")
                        .HasFilter("is_archived = false");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Verification.UserDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_superseded");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("review_note");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_documents_status_updated_at");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("ix_documents_user_id_type");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("CocoRider.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_passenger_id");

                    b.HasOne("CocoRider.Domain.Trips.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trips_trip_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Messaging.Message", b =>
                {
                    b.HasOne("CocoRider.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_bookings_booking_id");

                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_recipient_id");

                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Notifications.DeviceToken", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_tokens_users_user_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Reviews.Review", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_author_id");

                    b.HasOne("CocoRider.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_bookings_booking_id");

                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_subject_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Tracking.TripPosition", b =>
                {
                    b.HasOne("CocoRider.Domain.Trips.Trip", null)
                        .WithOne()
                        .HasForeignKey("CocoRider.Domain.Tracking.TripPosition", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_positions_trips_trip_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Tracking.TripShare", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_shares_users_created_by_id");

                    b.HasOne("CocoRider.Domain.Trips.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_shares_trips_trip_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Trips.Trip", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_users_driver_id");

                    b.HasOne("CocoRider.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_vehicles_vehicle_id");

                    b.OwnsOne("CocoRider.Domain.Trips.TripLocation", "Destination", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("destination_city");

                            b1.Property<string>("Landmark")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("destination_landmark");

                            b1.Property<Point>("Point")
                                .IsRequired()
                                .HasColumnType("geography (point, 4326)")
                                .HasColumnName("destination_point");

                            b1.HasKey("TripId");

                            b1.HasIndex("City")
                                .HasDatabaseName("ix_trips_destination_city");

                            b1.HasIndex("Point")
                                .HasDatabaseName("ix_trips_destination_point");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Point"), "gist");

                            b1.ToTable("trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("fk_trips_trips_id");
                        });

                    b.OwnsOne("CocoRider.Domain.Trips.TripLocation", "Origin", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origin_city");

                            b1.Property<string>("Landmark")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("origin_landmark");

                            b1.Property<Point>("Point")
                                .IsRequired()
                                .HasColumnType("geography (point, 4326)")
                                .HasColumnName("origin_point");

                            b1.HasKey("TripId");

                            b1.HasIndex("City")
                                .HasDatabaseName("ix_trips_origin_city");

                            b1.HasIndex("Point")
                                .HasDatabaseName("ix_trips_origin_point");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Point"), "gist");

                            b1.ToTable("trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("fk_trips_trips_id");
                        });

                    b.Navigation("Destination")
                        .IsRequired();

                    b.Navigation("Origin")
                        .IsRequired();
                });

            modelBuilder.Entity("CocoRider.Domain.Users.Strike", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany("Strikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_strikes_users_user_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Vehicles.Vehicle", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_owner_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Verification.UserDocument", b =>
                {
                    b.HasOne("CocoRider.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_users_user_id");
                });

            modelBuilder.Entity("CocoRider.Domain.Users.User", b =>
                {
                    b.Navigation("Strikes");
                });
#pragma warning restore 612, 618
        }
    }
}
